version: "3.0"

services:
  openapi_mock:
    container_name: coopera_platform
    image: jormaechea/open-api-mocker
    ports:
      - "8082:8080"
    volumes:
      - ./schema.json:/app/schema.json
    environment:
      OPEN_API_FILE: /app/schema.json
      PORT: 5000

  openapi_swagger:
    container_name: coopera_mock_swagger
    image: swaggerapi/swagger-ui
    ports:
      - "81:8080"
    environment:
      SWAGGER_JSON: /app/schema.json
      BASE_URL: /coopera_container
    volumes:
      - ./schema.json:/app/schema.json
    depends_on:
      - openapi_mock